

export const GET_TODO_DATA_REQUEST = "GET_TODO_DATA_REQUEST"
export const GET_TODO_DATA_SUCCESS = "GET_TODO_DATA_SUCCESS"
export const GET_TODO_DATA_FAILURE = "GET_TODO_DATA_FAILURE"


export const DELETE_TODO_DATA_REQUEST= "DELETE_TODO_DATA_REQUEST"
export const DELETE_TODO_DATA_SUCCESS= "DELETE_TODO_DATA_SUCCESS"
export const DELETE_TODO_DATA_FAILURE= "DELETE_TODO_DATA_FAILURE"

export const ADD_TODO_DATA_REQUEST= "ADD_TODO_DATA_REQUEST"
export const ADD_TODO_DATA_SUCCESS= "ADD_TODO_DATA_SUCCESS"
export const ADD_TODO_DATA_FAILURE= "ADD_TODO_DATA_FAILURE"

export const EDIT_TODO_DATA_REQUEST= "EDIT_TODO_DATA_REQUEST"
export const EDIT_TODO_DATA_SUCCESS= "EDIT_TODO_DATA_SUCCESS"
export const EDIT_TODO_DATA_FAILURE= "EDIT_TODO_DATA_FAILURE"